# API Keys for LLM services
OPENAI_API_KEY=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
GEMINI_API_KEY=AIzaSyBnCMPuoaFmdt7QdoIZat3uFcST_pRcEl4

# Set to: OPENAI, GEMINI, OPENAI-CLASSES, GEMINI-CLASSES
AI_LLM=GEMINI-CLASSES

# Logging configuration: OFF, ERROR, WARN, INFO, DEBUG, TRACE
LOG_LEVEL=OFF

TEMPERATURE=None
MAX_TOKENS=1000
